package common.util;

public enum Etat {DEMARRE, SAISIE_NB_JOUEURS, ATTENTE_CONNECTION_JOUEURS,ATTENTE_NOM_JOUEURS, CHOIX_FAMILLE, CHOISIR_LES_TERRITOIRES_DEMARRAGE, PLACER_LES_TROUPES_DEMARRAGE, TOUR_DE_JEU}

