package common;

public enum ClientCommandes {
    CONNECT,WELCOME,SEND_NAME, CHAT, TOUS_CONNECTES,LANCE_1DE_START,RESULTAT_1_DE,INFO,FAIRE_CHOIX_FAMILLE,JOUEUR_A_FAIT_CHOIX_FAMILLE,PLACER_LES_TROUPES_DEMARRAGE
}
